checkpoint_dir: experiments_checkpoints\supervised_mobilenetv3
config_dir: configuration_files\automated_saves\supervised_mobilenetv3
criterion:
  name: crossentropy
  params:
    temperature: 0.1
data:
  batch_size: 256
  directory: sketch_recvis2024
  num_workers: 8
  shuffle: true
  transform: simclr
early_stopping:
  min_delta: 0.001
  mode: min
  patience: 5
epochs: 40
experiment_name: Supervised Sim CLR Mobile Net V3
gradient_clipping: 1.0
log_dir: experiments_logs\supervised_mobilenetv3
log_interval: 1
mixed_precision: true
mixed_precision_level: float16
model:
  fix_encoder: true
  head: simclr
  name: mobilenetv3
  pretrained: true
  supervised: true
  weights_path: experiments_checkpoints\unsupervised_mobilenetv3\unsupervised_mobilenetv3_best.pth
optimizer:
  betas: null
  lr: 0.001
  momentum: null
  name: adamw
  weight_decay: 1.0e-05
save_interval: 1
scheduler:
  name: cosine
  params:
    T_max: 20
    eta_min: 1.0e-06
seed: 1
use_cuda: true
