checkpoint_dir: experiments_checkpoints\unsupervised_simclr
config_dir: configuration_files\automated_saves
criterion:
  name: simclr
  params:
    temperature: 0.05
data:
  batch_size: 256
  directory: sketch_recvis2024
  num_workers: 8
  shuffle: true
  transform: simclr
early_stopping:
  min_delta: 0.001
  mode: min
  patience: 5
epochs: 50
experiment_name: Unsupervised Sim CLR
gradient_clipping: 1.0
log_dir: experiments_logs\unsupervised_simclr
log_interval: 1
mixed_precision: false
mixed_precision_level: float16
model:
  name: mobilenetv3
  pretrained: true
  supervised: false
  weights_path: null
optimizer:
  betas: null
  lr: 0.001
  momentum: null
  name: adamw
  weight_decay: 1.0e-05
save_interval: 1
scheduler:
  name: cosine
  params:
    T_max: 50
    eta_min: 1.0e-06
seed: 1
use_cuda: true
