checkpoint_dir: experiments_checkpoints\supervised_resnet18
config_dir: configuration_files\automated_saves\supervised_resnet18
criterion:
  name: crossentropy
  params:
    temperature: 0.1
data:
  batch_size: 512
  directory: sketch_recvis2024
  num_workers: 8
  shuffle: true
  transform: basic
early_stopping:
  min_delta: 0.001
  mode: min
  patience: 5
epochs: 40
experiment_name: Supervised Sim CLR Resnet 18
gradient_checkpointing: false
gradient_clipping: null
log_dir: experiments_logs\supervised_resnet18
log_interval: 1
mixed_precision: false
mixed_precision_level: float32
model:
  fix_encoder: true
  head: simclr
  name: resnet18
  pretrained: true
  supervised: true
  weights_path: good_models\unsupervised_resnet18_3_best.pth
optimizer:
  betas: null
  lr: 0.01
  momentum: null
  name: adamw
  weight_decay: 0.0
save_interval: 1
scheduler:
  name: cosine
  params:
    T_max: 40
    eta_min: 1.0e-06
seed: 1
use_cuda: true
