# This is the configuration file for the unsupervised SimCLR experiment
experiment_name: Supervised Sim CLR Mobile Net V3
checkpoint_dir: experiments_checkpoints/supervised_mobilenetv3/
log_dir: experiments_logs/supervised_mobilenetv3/
log_interval: 1
config_dir: configuration_files/automated_saves/supervised_mobilenetv3/ # Directory where the configuration file will be saved with the same name as the experiment name
epochs: 40
seed: 1
# mixed_precision: true
# mixed_precision_level: float16
# gradient_clipping: 1.0

model:
  name: mobilenetv3
  pretrained: true
  supervised: true
  weights_path: experiments_checkpoints/unsupervised_mobilenetv3/unsupervised_mobilenetv3_best.pth
  fix_encoder: true
  head: simclr # linear, simclr

criterion:
  name: crossentropy

optimizer:
  name: adamw
  lr: 0.01
  weight_decay: 1.0e-5

scheduler:
  name: cosine
  params:
    T_max: 40
    eta_min: 1.0e-6

data:
  directory: sketch_recvis2024/
  transform: basic
  batch_size: 768
  num_workers: 8

early_stopping:
  min_delta: 0.001
  patience: 5