# This is the configuration file for the unsupervised SimCLR experiment
experiment_name: Supervised Sim ViT
checkpoint_dir: experiments_checkpoints/supervised_vit/
log_dir: experiments_logs/supervised_vit/
log_interval: 1
config_dir: configuration_files/automated_saves/supervised_vit/ # Directory where the configuration file will be saved with the same name as the experiment name
epochs: 20
seed: 1
mixed_precision: true
mixed_precision_level: float16
gradient_clipping: 1.0


model:
  name: vit
  pretrained: true
  supervised: true
  weights_path: experiments_checkpoints/unsupervised_vit/unsupervised_vit_best.pth


criterion:
  name: crossentropy

optimizer:
  name: adamw
  lr: 0.001
  weight_decay: 1.0e-5

scheduler:
  name: cosine
  params:
    T_max: 20
    eta_min: 1.0e-6

data:
  directory: sketch_recvis2024/
  transform: simclr
  batch_size: 48
  num_workers: 8

early_stopping:
  min_delta: 0.001
  patience: 5