checkpoint_dir: experiments_checkpoints\supervised_squeezenet_scratch
config_dir: configuration_files\automated_saves\supervised_squeezenet_scratch
criterion:
  name: crossentropy
  params:
    temperature: 0.1
data:
  batch_size: 256
  directory: sketch_recvis2024
  num_workers: 8
  shuffle: true
  transform: simclr
early_stopping:
  min_delta: 0.001
  mode: min
  patience: 5
epochs: 20
experiment_name: Supervised Sim CLR Squeeze Net
gradient_checkpointing: false
gradient_clipping: 1.0
log_dir: experiments_logs\supervised_squeezenet_scratch
log_interval: 1
mixed_precision: true
mixed_precision_level: float16
model:
  fix_encoder: false
  head: linear
  name: squeezenet1_1
  pretrained: true
  supervised: true
  weights_path: null
optimizer:
  betas: null
  lr: 0.001
  momentum: null
  name: adamw
  weight_decay: 1.0e-05
save_interval: 1
scheduler:
  name: cosine
  params:
    T_max: 20
    eta_min: 1.0e-06
seed: 1
use_cuda: true
